[package]
name = "markdown-to-standalone-html"
description = "Create a standalone HTML file from Markdown with basic CSS"
version = "0.1.0"
license = "MIT"
repository = "https://github.com/EdJoPaTo/markdown-to-standalone-html"
authors = ["EdJoPaTo <markdown-to-standalone-html@edjopato.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
handlebars = "3"
markdown = "0.3"
regex = "1"
serde_json = "1"

[dependencies.clap]
version = "2"
features = ["wrap_help"]
